//import app.cash.licensee.SpdxId
import com.android.build.gradle.api.AndroidBasePlugin
import org.jetbrains.kotlin.gradle.dsl.JvmDefaultMode
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.android.test) apply false
    alias(libs.plugins.androidx.baselineprofile)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.parcelize)
    alias(libs.plugins.kotlin.serialization)
//    alias(libs.plugins.google.ksp)
    alias(libs.plugins.google.protobuf)
//    alias(libs.plugins.cash.licensee)
    alias(libs.plugins.rikka.refine)
    alias(libs.plugins.diffplug.spotless)
    id "org.jetbrains.kotlin.kapt" version "2.3.0"
    id 'com.google.gms.google-services' version '4.4.4' apply false
}


allprojects {
    plugins.withType(AndroidBasePlugin).configureEach {
        android {
            buildToolsVersion "36.1.0"
            compileSdk {
                version = release(36) {
                    minorApiLevel = 1
                }
            }
            defaultConfig {
                minSdk 26
                targetSdk 35
                vectorDrawables.useSupportLibrary = true
            }
            lint {
                abortOnError true
                checkReleaseBuilds false
            }
            compileOptions {
                sourceCompatibility = libs.versions.jdkRelease.get()
                targetCompatibility = libs.versions.jdkRelease.get()
            }
        }
        dependencies {
            implementation libs.androidx.core.ktx
        }
    }

    plugins.withId('com.google.protobuf') {
        protobuf {
            // Configure the protoc executable
            protoc {
                artifact = libs.protobuf.protoc.get().toString()
            }
            generateProtoTasks {
                all().configureEach { task ->
                    task.builtins {
                        remove java
                        java {
                            option "lite"
                        }
                    }
                }
            }
        }
        dependencies {
            implementation libs.protobuf.javalite
        }
    }

    plugins.withType(JavaBasePlugin).configureEach {
        java {
            sourceCompatibility = libs.versions.jdkRelease.get()
            targetCompatibility = libs.versions.jdkRelease.get()
        }
    }

    tasks.withType(KotlinCompile).configureEach {
        compilerOptions {
            jvmDefault = JvmDefaultMode.ENABLE
            jvmTarget = JvmTarget.fromTarget(libs.versions.jdkRelease.get())
        }
    }

    configurations.configureEach {
        resolutionStrategy.eachDependency {
            // Fix duplicate class kotlinx.android.parcel.* found in these 2 dependencies.
            if (requested.module == libs.kotlin.androidExtensionRuntime.get().module) {
                useTarget(libs.kotlin.parcelizeRuntime)
            }
        }
    }

    ext {
        FRAMEWORK_PREBUILTS_DIR = "$rootDir/prebuilts/libs"

        addFrameworkJar = { String name ->
            def frameworkJar = new File(FRAMEWORK_PREBUILTS_DIR, name)
            if (!frameworkJar.exists()) {
                throw new IllegalArgumentException("Framework jar path ${frameworkJar.path} doesn't exist")
            }
            gradle.projectsEvaluated {
                tasks.withType(JavaCompile).configureEach {
                    // Make sure the frameworkJar is always first in the classpath.
                    classpath = files(frameworkJar, classpath)
                }
                tasks.withType(KotlinCompile).configureEach {
                    // Make sure the frameworkJar is always first in the classpath.
                    libraries.setFrom files(frameworkJar, libraries)
                }
            }
            dependencies {
                compileOnly files(frameworkJar)
            }
        }

        compileOnlyCommonJars = {
            dependencies {
                compileOnly fileTree(dir: FRAMEWORK_PREBUILTS_DIR, include: 'SystemUI-core.jar')
                compileOnly fileTree(dir: FRAMEWORK_PREBUILTS_DIR, include: 'SystemUI-statsd.jar')
                compileOnly fileTree(dir: FRAMEWORK_PREBUILTS_DIR, include: 'WindowManager-Shell-15.jar')

                compileOnly projects.compatLib
                compileOnly projects.compatLib.compatLibVQ
                compileOnly projects.compatLib.compatLibVR
                compileOnly projects.compatLib.compatLibVS
                compileOnly projects.compatLib.compatLibVT
                compileOnly projects.compatLib.compatLibVU
                compileOnly projects.compatLib.compatLibVV
            }
        }
    }
}

final def buildCommit = providers.exec {
    commandLine('git', 'rev-parse', '--short=7', 'HEAD')
}.standardOutput.asText.get().trim()

final def ciBuild = System.getenv("CI") == "true"
final def ciRef = System.getenv("GITHUB_REF") ?: ""
final def ciRunNumber = System.getenv("GITHUB_RUN_NUMBER") ?: ""
final def isReleaseBuild = ciBuild && ciRef.contains("beta")
final def devReleaseName = ciBuild ? "Dev.(#${ciRunNumber})" : "Dev.(${buildCommit})"
final def version = "15"
final def releaseName = "Beta 2"
final def versionDisplayName = "${version}.${isReleaseBuild ? releaseName : devReleaseName}"
final def majorVersion = versionDisplayName.split("\\.")[0]

final def quickstepMinSdk = "29"
final def quickstepMaxSdk = "35"

android {
    namespace "com.android.launcher3"
    defaultConfig {
        // Lawnchair Launcher 15.0 Beta 2
        // See CONTRIBUTING.md#versioning-scheme
        versionCode 100300
        versionName "1.3.0"
        buildConfigField "String", "VERSION_DISPLAY_NAME", "\"${versionDisplayName}\""
        buildConfigField "String", "MAJOR_VERSION", "\"${majorVersion}\""
        buildConfigField "String", "COMMIT_HASH", "\"${buildCommit}\""
        buildConfigField "boolean", "ENABLE_AUTO_INSTALLS_LAYOUT", "false"

        manifestPlaceholders.quickstepMinSdk = quickstepMinSdk
        manifestPlaceholders.quickstepMaxSdk = quickstepMaxSdk
        buildConfigField "int", "QUICKSTEP_MIN_SDK", quickstepMinSdk
        buildConfigField "int", "QUICKSTEP_MAX_SDK", quickstepMaxSdk
        vectorDrawables.useSupportLibrary = true
        ndk {
            abiFilters  'armeabi-v7a','arm64-v8a'
        }
    }

    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach {
            def channel = variant.productFlavors.last().name
            outputFileName = "WalkWinCash_${variant.versionName}_${channel}_${variant.buildType.name}.apk"
        }
    }


    androidResources {
        generateLocaleConfig true
    }

    buildFeatures {
        aidl true
        buildConfig true
        resValues true
        compose true
        viewBinding true
    }

    packagingOptions.resources.excludes += [
        "**/*.proto",
        "**/*.bin",
        "**/*.java",
        "**/*.properties",
        "**/*.version",
        "**/*.*_module",
        "com/**",
        "google/**",
        "kotlin/**",
        "kotlinx/**",
        "okhttp3/**",
        "META-INF/services/**",
        "META-INF/com/**",
        "META-INF/licenses/**",
        "META-INF/AL2.0",
        "META-INF/LGPL2.1",
    ]

    // Load all proguard configs from AOSP
    def proguardFilesFromAosp = allprojects
        .collect { it.file("proguard.flags") }
        .findAll { it.exists() }
        .toArray()

    def releaseSigning
    try {
        releaseSigning = signingConfigs.create("release") {
            storeFile file('keystore/release.keystore')
            storePassword 'unlimitedrefills2025'
            keyAlias 'unlimited_refills'
            keyPassword 'unlimitedrefills2025'
        }
    } catch (Exception ignored) {
        releaseSigning = signingConfigs.debug
    }

    buildTypes {
        all {
            signingConfig releaseSigning

            applicationVariants.configureEach { variant ->
                variant.outputs.configureEach {
                    def channel = variant.productFlavors.last().name
                    // Override signingConfig to debug if the "nightly" flavor is selected
                    if (channel.any { it == "nightly" }) {
                        signingConfig = signingConfigs.debug
                    }
                }
            }
            pseudoLocalesEnabled true
        }

        debug {
            applicationIdSuffix ".debug"
            resValue("string", "derived_app_name", "Walk (Debug)")
        }

        release {
            resValue("string", "derived_app_name", "Walk")
            minifyEnabled true
            shrinkResources true
            proguardFiles proguardFilesFromAosp + "proguard.pro" + getDefaultProguardFile('proguard-android-optimize.txt') + "proguard-rules.pro"
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled true
    }

    dependenciesInfo {
        includeInApk = false
        includeInBundle = false
    }

    // See: https://developer.android.com/studio/build/build-variants#flavor-dimensions
    flavorDimensions += ["app", "recents", "channel"]

    productFlavors {
        lawn {
            dimension "app"
        }

        withQuickstep {
            dimension "recents"
            minSdk 26
        }

        github {
            applicationId 'com.ur.apps.walk'
            dimension "channel"
        }

        nightly {
            applicationId 'com.ur.apps.walk.nightly'
            dimension "channel"
        }

        play {
            applicationId "com.ur.apps.walk"
            dimension "channel"
            isDefault true
        }

        configureEach {
            resValue("string", "launcher_component", "${applicationId}/app.lawnchair.LawnchairLauncher")
        }
    }

    sourceSets {
        main {
            res.srcDirs = ['res']
            java.srcDirs = ['src', 'src_plugins']
            manifest.srcFile 'AndroidManifest-common.xml'
            proto {
                srcDirs = ['protos/', 'quickstep/protos_overrides/']
            }
        }

        lawn {
            java.srcDirs = ['src_flags', 'src_shortcuts_overrides', 'lawnchair/src', 'tests/shared']
            aidl.srcDirs = ['lawnchair/aidl']
            res.srcDirs = ['lawnchair/res', 'platform_frameworks_libs_systemui/animationlib/res']
            manifest.srcFile "lawnchair/AndroidManifest.xml"
            assets {
                srcDirs 'lawnchair/assets'
            }
            proto {
                srcDirs = ['lawnchair/protos/']
            }
        }

        github {
            manifest.srcFile "github/AndroidManifest.xml"
        }

        nightly {
            manifest.srcFile "nightly/AndroidManifest.xml"
        }

        lawnWithQuickstepGithub {
            manifest.srcFile "quickstep/AndroidManifest-launcher.xml"
        }

        lawnWithQuickstepNightly {
            manifest.srcFile "quickstep/AndroidManifest-launcher.xml"
        }

        lawnWithQuickstepPlay {
            manifest.srcFile "quickstep/AndroidManifest-launcher.xml"
        }

        withQuickstep {
            res.srcDirs = ['quickstep/res', 'quickstep/recents_ui_overrides/res']
            java.srcDirs = ['quickstep/src', 'quickstep/recents_ui_overrides/src']
            manifest.srcFile "quickstep/AndroidManifest.xml"
        }
    }
}

composeCompiler {
    stabilityConfigurationFiles.addAll(
        layout.projectDirectory.file("compose_compiler_config.conf"),
    )
    reportsDestination = layout.buildDirectory.dir("compose_build_reports")
}

addFrameworkJar('framework-15.jar')

dependencies {
    implementation projects.iconloaderlib
    implementation projects.searchuilib
    implementation projects.animationlib

    // Recents lib dependency
    withQuickstepCompileOnly projects.hiddenApi
    withQuickstepImplementation projects.shared
    withQuickstepImplementation projects.anim
    withQuickstepImplementation projects.unfold
    withQuickstepImplementation projects.viewcapture
    withQuickstepImplementation projects.log
    withQuickstepCompileOnly projects.plugin
    withQuickstepImplementation projects.plugincore
    withQuickstepCompileOnly projects.common

    // QuickSwitch Compat
    withQuickstepImplementation projects.compatLib
    withQuickstepImplementation projects.compatLib.compatLibVQ
    withQuickstepImplementation projects.compatLib.compatLibVR
    withQuickstepImplementation projects.compatLib.compatLibVS
    withQuickstepImplementation projects.compatLib.compatLibVT
    withQuickstepImplementation projects.compatLib.compatLibVU
    withQuickstepImplementation projects.compatLib.compatLibVV
    withQuickstepImplementation projects.wmshell
    withQuickstepImplementation projects.flags
    implementation libs.androidx.dynamicanimation

    implementation fileTree(dir: FRAMEWORK_PREBUILTS_DIR, include: 'SystemUI-statsd-15.jar')
    implementation fileTree(dir: FRAMEWORK_PREBUILTS_DIR, include: 'WindowManager-Shell-15.jar')
    withQuickstepCompileOnly fileTree(dir: FRAMEWORK_PREBUILTS_DIR, include: 'framework-15.jar')

    coreLibraryDesugaring libs.android.desugarJdkLibs

    implementation libs.androidx.profileinstaller
    baselineProfile projects.baselineProfile

    implementation libs.androidx.recyclerview
    implementation libs.androidx.preference.ktx

    implementation libs.kotlinx.coroutines.android
    implementation libs.kotlinx.serialization.json
    implementation libs.chickenhook.restrictionbypass
    implementation libs.rikka.refine.runtime

    implementation platform(libs.compose.bom)
    implementation libs.compose.ui
    implementation libs.compose.ui.util
    debugImplementation libs.compose.ui.tooling
    implementation libs.compose.ui.tooling.preview
    implementation libs.compose.ui.google.fonts
    implementation libs.compose.foundation
    implementation libs.compose.material.icons
    implementation libs.compose.runtime.livedata
    implementation libs.compose.material3
    implementation libs.compose.material3.windowSizeClass
    implementation libs.androidx.activity.compose
    implementation libs.androidx.lifecycle.viewmodel.compose
    implementation libs.androidx.navigation.compose
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.palette.ktx
    implementation libs.androidx.slice.core
    implementation libs.bundles.accompanist
    implementation libs.google.material
    implementation libs.material.motion.compose
    implementation libs.kdrag0n.colorkt
    implementation libs.coil.compose
    implementation libs.xdrop.fuzzywuzzy

    implementation libs.bundles.opto
    implementation libs.androidx.datastore.preferences

    implementation libs.bundles.retrofit

    implementation libs.bundles.room
//    ksp libs.room.compiler

    implementation libs.libsu.service

    // Persian Date
    implementation libs.persian.date

    implementation libs.airbnb.lottie

    // Compose drag and drop library
    implementation libs.reorderable

    // Smartspacer
    implementation(libs.smartspacer.sdk) {
        exclude group: "com.github.skydoves", module: "balloon"
    }

    implementation libs.hoko.blur

    implementation libs.androidx.window


    // walk  start

    implementation fileTree(dir: "$rootDir/lawnchair/libs", include: ['*.jar', '*.aar'])

    implementation libs.play.services.measurement.api
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material

    api "com.blankj:utilcodex:1.31.1"
    api "com.google.code.gson:gson:2.10"
    api 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.google.android.gms:play-services-ads-identifier:18.0.1'
    implementation 'com.android.installreferrer:installreferrer:2.2'
    api 'com.tenjin:android-sdk:1.16.6'
    implementation 'cn.thinkingdata.android:ThinkingAnalyticsSDK:3.0.2'
    implementation("androidx.ads:ads-identifier:1.0.0-alpha01")
    implementation("com.google.guava:guava:28.0-android")

    implementation 'com.applovin:applovin-sdk:+'
    //Anythink (Necessary)
    implementation "com.anythink.sdk:core-tpn:6.4.56.1"
    implementation "com.anythink.sdk:nativead-tpn:6.4.56.1"
    implementation "com.anythink.sdk:banner-tpn:6.4.56.1"
    implementation "com.anythink.sdk:interstitial-tpn:6.4.56.1"
    implementation "com.anythink.sdk:rewardedvideo-tpn:6.4.56.1"
    implementation "com.anythink.sdk:splash-tpn:6.4.56.1"
    //Androidx (Necessary)
    implementation "androidx.appcompat:appcompat:1.1.0"
    implementation "androidx.browser:browser:1.4.0"
    //Vungle
    implementation "com.anythink.sdk:adapter-tpn-vungle:6.4.56"
    implementation "com.vungle:vungle-ads:7.4.3"
    implementation "com.google.android.gms:play-services-basement:18.1.0"
    implementation "com.google.android.gms:play-services-ads-identifier:18.0.1"
    //UnityAds
    implementation "com.anythink.sdk:adapter-tpn-unityads:6.4.56.1"
    implementation "com.unity3d.ads:unity-ads:4.13.1"
    //Bigo
    implementation "com.anythink.sdk:adapter-tpn-bigo:6.4.56"
    implementation "com.bigossp:bigo-ads:5.1.0"
    //Pangle
    implementation "com.anythink.sdk:adapter-tpn-pangle-nonchina:6.4.56"
    implementation "com.pangle.global:ads-sdk:6.4.0.6"
    implementation "com.google.android.gms:play-services-ads-identifier:18.0.1"
//
//    //Kwai
//    implementation "com.anythink.sdk:adapter-tpn-kwai:6.4.56"
//    implementation "io.github.kwainetwork:adimplementation:1.2.15"
//    implementation "io.github.kwainetwork:adImpl:1.2.15"
//    implementation "androidx.media3:media3-exoplayer:1.0.0-alpha01"
//    implementation "androidx.appcompat:appcompat:1.2.0"
//    implementation "com.google.android.material:material:1.2.1"
//    implementation "androidx.annotation:annotation:1.2.0"
//    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.4.10"
//    implementation "com.google.android.gms:play-services-ads-identifier:18.0.1"

    //Facebook
    implementation "com.anythink.sdk:adapter-tpn-facebook:6.4.56"
    implementation "com.facebook.android:audience-network-sdk:6.18.0"
    implementation "androidx.annotation:annotation:1.0.0"
    //Admob
    implementation "com.anythink.sdk:adapter-tpn-admob:6.4.56"
    api "com.google.android.gms:play-services-ads:23.6.0"
    //Inmobi
    implementation "com.anythink.sdk:adapter-tpn-inmobi:6.4.12.2"
    implementation "com.inmobi.monetization:inmobi-ads-kotlin:10.8.0"
    //AppLovin
    implementation "com.anythink.sdk:adapter-tpn-applovin:6.4.56.1"
    implementation "com.applovin:applovin-sdk:13.1.0"
    //Mintegral
    implementation "com.anythink.sdk:adapter-tpn-mintegral-nonchina:6.4.12.9"
    implementation "com.mbridge.msdk.oversea:mbridge_android_sdk:16.9.11"
    implementation "androidx.recyclerview:recyclerview:1.1.0"
    //Chartboost
    implementation "com.anythink.sdk:adapter-tpn-chartboost:6.4.56"
    implementation "com.chartboost:chartboost-sdk:9.8.2"
    implementation "com.chartboost:chartboost-mediation-sdk:4.9.2"
    implementation "com.chartboost:chartboost-mediation-adapter-chartboost:4.9.8.1.0"
    implementation "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:1.0.0"
    api 'com.squareup.retrofit2:converter-gson:2.9.0'
    api "com.squareup.okhttp3:logging-interceptor:4.10.0"
    api "com.squareup.okhttp3:okhttp:4.10.0"
    api "com.squareup.retrofit2:converter-scalars:2.9.0"
    api "com.squareup.retrofit2:retrofit:2.9.0"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.1"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1"
    //Yandex
    implementation "com.anythink.sdk:adapter-tpn-yandex:6.4.56.1"
    implementation "com.yandex.android:mobileads:7.10.0"
    //Fyber
    implementation "com.anythink.sdk:adapter-tpn-fyber:6.4.56"
    implementation "com.fyber:marketplace-sdk:8.3.5"
    implementation "com.google.android.gms:play-services-ads-identifier:18.0.1"
    //Tramini
    implementation "com.anythink.sdk:tramini-plugin-tpn:6.4.56"
    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.squareup.okhttp3:okhttp:4.9.3'
    implementation 'com.github.megatronking.stringfog:xor:4.0.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.3'

    // Room dependencies
    implementation libs.androidx.room.runtime
    implementation libs.androidx.lifecycle.process
//    implementation libs.play.services.ads.api
//    implementation libs.play.services.ads.api
    kapt libs.androidx.room.compiler
    implementation libs.androidx.room.ktx
    implementation libs.androidx.core.ktx
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.activity.compose
    implementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.ui
    implementation libs.androidx.ui.graphics
    implementation libs.androidx.ui.tooling.preview
    implementation libs.androidx.material3
    implementation libs.androidx.appcompat
    implementation libs.material
//    implementation project(':ad')

    // Material Design
    implementation 'com.google.android.material:material:1.11.0'

    // MPAndroidChart 图表库
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'

    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
    androidTestImplementation platform(libs.androidx.compose.bom)
    androidTestImplementation libs.androidx.ui.test.junit4
    debugImplementation libs.androidx.ui.tooling
    debugImplementation libs.androidx.ui.test.manifest

    implementation 'com.github.bumptech.glide:glide:4.16.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'

    // Gson for JSON parsing
    implementation 'com.google.code.gson:gson:2.10.1'

    // ViewPager2
    implementation 'androidx.viewpager2:viewpager2:1.0.0'
    // AutoSize
    implementation 'com.github.JessYanCoding:AndroidAutoSize:v1.2.1'

    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.squareup.okhttp3:okhttp:4.9.3'
    implementation 'com.github.megatronking.stringfog:xor:4.0.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.3'

    // SwipeRefreshLayout for pull-to-refresh
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'

    // add firebase
    // Import the Firebase BoM
    implementation(platform("com.google.firebase:firebase-bom:34.5.0"))
    // When using the BoM, you don't specify versions in Firebase library dependencies
    // Add the dependency for the Firebase SDK for Google Analytics
    implementation("com.google.firebase:firebase-analytics")
    // TODO: Add the dependencies for any other Firebase products you want to use
    // See https://firebase.google.com/docs/android/setup#available-libraries
    // For example, add the dependencies for Firebase Authentication and Cloud Firestore
    implementation("com.google.firebase:firebase-auth")
    implementation('com.google.firebase:firebase-firestore') {
        exclude group: 'com.google.firebase', module: 'protolite-well-known-types'
    }
    // 确保你的项目里有这个，它包含了最新的类型定义
    implementation 'com.google.protobuf:protobuf-javalite:4.33.2'
    // walk end

}

//ksp {
//    arg("room.schemaLocation", "$projectDir/schemas")
//}


spotless {
    java {
        target("compatLib/**/src/**/*.java")
        googleJavaFormat().aosp()
        removeUnusedImports()
    }
    kotlin {
        target("lawnchair/src/**/*.kt")
        ktlint("1.8.0").customRuleSets([
            libs.composeRules.get().toString()
        ]).editorConfigOverride([
            "ktlint_compose_compositionlocal-allowlist": "disabled",
            "ktlint_compose_lambda-param-event-trailing": "disabled",
            "ktlint_compose_content-slot-reused": "disabled",
        ])
    }
}
//
//licensee {
//    allow(SpdxId.Apache_20)
//    allow(SpdxId.BSD_3_Clause)
//    allow(SpdxId.GPL_20_or_later)
//    allowDependency(libs.libsu.core)
//    allowDependency(libs.libsu.service)
//    allowUrl("https://github.com/patrykmichalik/opto/blob/master/LICENSE")
//    allowUrl("https://github.com/RikkaApps/HiddenApiRefinePlugin/blob/main/LICENSE")
//    allowUrl("https://opensource.org/licenses/mit-license.php")
//
//    bundleAndroidAsset = true
//    androidAssetReportPath = 'licenses.json'
//}
